/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyButton {
        "url": string;
    }
    interface MyComponent {
        "counter": number;
        "heading": string;
    }
    interface MyShadowComponent {
        "counter": number;
        "heading": string;
    }
}
declare global {
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyShadowComponentElement extends Components.MyShadowComponent, HTMLStencilElement {
    }
    var HTMLMyShadowComponentElement: {
        prototype: HTMLMyShadowComponentElement;
        new (): HTMLMyShadowComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-button": HTMLMyButtonElement;
        "my-component": HTMLMyComponentElement;
        "my-shadow-component": HTMLMyShadowComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyButton {
        "url"?: string;
    }
    interface MyComponent {
        "counter"?: number;
        "heading"?: string;
    }
    interface MyShadowComponent {
        "counter"?: number;
        "heading"?: string;
    }
    interface IntrinsicElements {
        "my-button": MyButton;
        "my-component": MyComponent;
        "my-shadow-component": MyShadowComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-button": LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-shadow-component": LocalJSX.MyShadowComponent & JSXBase.HTMLAttributes<HTMLMyShadowComponentElement>;
        }
    }
}
